name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:

    - name: Build
      run: |
      env:
        CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.REACT_APP_CLIENT_SECRET }}

    - name: Deploy
      run: |
      env:
        CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.REACT_APP_CLIENT_SECRET }}
